Dataset:
  trn_path: "../workspace/Datasets/Intel_Image_Classification/seg_train/buildings"
  tst_path: "../workspace/Datasets/Intel_Image_Classification/seg_train/buildings"
  vec_dim: 128
  batch_size: 8
  h: 64
  w: 64
  num_workers: 8
  pin_memory: True
Argumentation:
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
Model:
  GAN:
    G:
      PlainetGenVec:
        input_dim          : 128
        hidden_channels    : 512
        hidden_size        : 4
        out_channels       : 3
        kernel_size        : 4
        stride             : 2
        norm               : "BatchNorm"
        act                : "Relu"
        bias               : False
        dropout            : 0
        n_layers           : 4
        output_kernel_size : 3
        output_padding_mode: "zeros"
      OPT:
        Adam:
          lr: 1e-4
          betas: [0.5, 0.999]
      Init:
        normal_:
          mean: 0
          std: 0.2
    D:
      ResNet:
        block            : "ResBlock"
        n_blocks_list    : [1, 1, 1]
        stride_list      : [2, 2, 2]
        in_channels      : 3
        hidden_channels  : 32
        kernel_size      : 3
        kernel_size_first: 3
        stride_first     : 1
        use_bn_first     : False
        use_act_first    : True
        use_maxpool      : False
        norm             : "IdentityNorm"
        act:
          LeakyReLU:
            negative_slope: 0.1
        down_sample: "conv"
        bias: True
        use_short_cut: False
        num_classes: 2
      OPT:
        Adam:
          lr: 1e-4
          betas: [ 0.5, 0.999 ]
      Init:
        normal_:
          mean: 0
          std: 0.2

    Train:
      GAN_loss: "vanilla"
      save_imgs: 20
      iterations: 50000
      print_freq: 50
      save_freq: 1000
      output: "../workspace/Output/GAN/Vanilla_GAN_Intel_Buildings_64"
      device: [0]
