Dataset:
  name: "CIFAR10"
  root_path: "../workspace/Datasets"
  batch_size: 128
  h: 32
  w: 32
  num_workers: 4
  pin_memory: True
Argumentation:
  RandomHorizontalFlip:
    p: 0.5
  RandomCrop:
    size: [32, 32]
    padding: 4
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
Model:
  DiracNet:
    in_channels    : 3
    hidden_channels: 16
    n_blocks_list  : [8, 8, 8]
    stride_list    : [2, 2, 2]
    stride_factor  : 2
    pool_size      : 3
    k              : 5
    num_classes    : 10
    last_act       : "IdentityAct"
    conv           :
      ConvNormAct:
        norm: "BatchNorm"
        act : "ReLU"
        conv:
          DiracConv2d:
            kernel_size: 3
            bias: False
            padding: 1
  OPT:
    SGD:
      lr: 0.1
      momentum: 0.9
      weight_decay: 1e-4
  Scheduler:
    MultiStepLR: 
      gamma: 0.2
      milestones: [23400, 46800, 62400]
  Init:
    kaiming_normal_:
      mode: "fan_in"
      nonlinearity: "relu"

Train:
  iterations: 75000
  save_freq: 500
  output: "../workspace/Output/DiracNet/DiracNet_20_5_EXP"
  keep_gradients: False
  device: [0]