Dataset:
  name: "CIFAR10"
  root_path: "../workspace/Datasets"
  batch_size: 128
  h: 32
  w: 32
  num_workers: 4
  pin_memory: True
Argumentation:
  RandomHorizontalFlip:
    p: 0.5
  RandomCrop:
    size: [32, 32]
    padding: 4
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
Model:
  VGG:
    in_channels    : 3
    hidden_channels: 64
    n_blocks_list  : [2, 3, 4, 4]
    stride_list    : [2, 2, 2, 2]
    stride_factor  : 2
    pool_size      : 3
    fc_in_dim      : 2048
    fc_out_dim     : 1024
    num_classes    : 10
    last_act       : "IdentityAct"
    conv           :
      ConvNormAct:
        norm: "IdentityNorm"
        act: "ReLU"
        conv:
          RepVGGBlock:
            kernel_size: 3
            padding: 1
  OPT:
    SGD:
      lr: 0.1
      momentum: 0.9
      weight_decay: 5e-4
  Scheduler:
    MultiStepLR:
      gamma: 0.2
      milestones: [23400, 46800, 62400]
  Init:
    kaiming_normal_:
      mode: "fan_in"
      nonlinearity: "relu"

Train:
  iterations: 78000
  save_freq: 500
  deploy: True
  deploy_test: True
  output: "../workspace/Output/RepVGG/RepVGG_VGG-16_CIFAR10_EXP"
  keep_gradients: False
  device: [0]  # set to [0, 1, ...] for multiple GPUs; set "cpu" for cpu