Dataset:
  trn_path: "Datasets/CIFAR-10/train"
  tst_path: "Datasets/CIFAR-10/test"
  batch_size: 64
  h: 32
  w: 32
Argumentation:
  RandomHorizontalFlip:
    p: 0.5
  RandomCrop:
    size: [32, 32]
    padding: 4
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
Model:
  ResNet:
    block: "ResBlock"
    n_blocks_list: [3, 8, 13, 3]
    stride_list: [1, 2, 2, 2]
    in_channels: 3
    hidden_channels: 64
    kernel_size: 3
    kernel_size_first: 3
    stride_first: 1
    norm: "BatchNorm"
    act: "Relu"
    down_sample: "conv"
    bias: False
    use_short_cut: True
    use_maxpool: False
    num_classes: 10
  OPT:
    SGD:
      lr: 1e-3
      momentum: 0.9
      weight_decay: 0

Train:
  iterations: 60000
  save_freq: 500
  output: "Output/ResNet_56-Layers_CIFAR10"
  keep_gradients: True
  device: "cuda"
