Dataset:
  name: "CIFAR10"
  root_path: "../Datasets"
  batch_size: 128
  in_channels: 3
  h: 32
  w: 32
Argumentation:
  zero_padding: 4
  random_horizontal_flip: 0.5
  random_crop: [32, 32]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
Model:
  ResNet:
    block: "ResBlock"
    n_blocks_list: [7, 7, 7]
    stride_list: [1, 2, 2]
    in_channels: 3
    hidden_channels: 16
    kernel_size: 3
    kernel_size_first: 3
    stride_first: 1
    norm: "BatchNorm"
    act: "Relu"
    down_sample: "interpolate"
    bias: True
    use_short_cut: True
    use_maxpool: False
    num_classes: 10
    device: "cuda"
  OPT:
    SGD:
      lr: 0.1
      momentum: 0.9
      weight_decay: 1e-4
  Scheduler:
    MultiStepLR: 
      gamma: 0.1
      milestones: [32000, 48000]
  Init:
    kaiming_normal_:
      mode: "fan_in"
      nonlinearity: "relu"

Train:
  iterations: 64000
  save_freq: 500
  output: "../Output/ResNet_44-Layers_CIFAR10_EXP"
  keep_gradients: True
