Dataset:
  name: "CIFAR10"
  root_path: "../workspace/Datasets"
  batch_size: 128
  h: 32
  w: 32
  num_workers: 16
  pin_memory: True
Argumentation:
  RandomHorizontalFlip:
    p: 0.5
  RandomCrop:
    size: [32, 32]
    padding: 4
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
Model:
  PlainOANet:
    in_channels    : 3
    hidden_channels: 16
    n_blocks_list  : [1, 5, 5, 5]
    stride_list    : [1, 1, 2, 2]
    stride_factor  : 2
    num_classes    : 10
    last_act       : "IdentityAct"
    use_pool       : False
    conv1          :
      ConvNormAct:
        norm: "BatchNorm"
        act: "ReLU"
        conv:
          Conv2d:
            kernel_size: 3
            bias: False
            padding: 1
    conv2:
      ResBlock:
        act: "ReLU"
        conv1:
          ConvNormAct:
            norm: "BatchNorm"
            act: "ReLU"
            conv:
              Conv2d:
                kernel_size: 3
                bias: False
                padding: 1
        conv2:
          ConvNormAct:
            norm: "BatchNorm"
            act: "IdentityAct"
            conv:
              Conv2d:
                kernel_size: 3
                bias: False
                padding: 1
        conv_sc:
          ConvNormAct:
            norm: "BatchNorm"
            act: "IdentityAct"
            conv:
              Conv2d:
                kernel_size: 1
                bias: False
                padding: 0
  OPT:
    SGD:
      lr: 0.1
      momentum: 0.9
      weight_decay: 1e-4
  Scheduler:
    MultiStepLR:
      gamma: 0.1
      milestones: [32000, 48000]
  Init:
    kaiming_normal_:
      mode: "fan_in"
      nonlinearity: "relu"

Train:
  iterations: 64000
  save_freq: 500
  output: "../workspace/Output/ResNet/ResNet_32-Layers_CIFAR10"
  keep_gradients: False
  device: [0]  # set to [0, 1, ...] for multiple GPUs; set "cpu" for cpu