Dataset:
  name: "CIFAR10"
  root_path: "Datasets"
  batch_size: 128
  h: 32
  w: 32
Argumentation:
  RandomHorizontalFlip:
    p: 0.5
  RandomCrop:
    size: [32, 32]
    padding: 4
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
Model:
  InceptionBN:
    "in_channels": 3
    "kernel_size_first": 3
    "stride_first": 1
    "maxpool_first": False
    "norm": "BatchNorm"
    "act": "Relu"
    "bias": False
    "dropout": 0.4
    "factorize_5x5": True
    "num_classes": 10
  OPT:
    SGD:
      lr: 0.001
      momentum: 0.9
      weight_decay: 1e-4
  Scheduler:
    MultiStepLR: 
      gamma: 0.1
      milestones: [32000, 48000]
  Init:
    kaiming_normal_:
      mode: "fan_in"
      nonlinearity: "relu"

Train:
  iterations: 64000
  save_freq: 500
  output: "Output/Inception/InceptionBN_kaimingInit"
  keep_gradients: False
  device: "cuda"

